import { UnsupportedFeatureError } from "@obinexusltd/obix-spec";
import type { DopIR, EmitMode, ObixScriptModel } from "@obinexusltd/obix-spec";

export interface EmitOptions {
  mode?: EmitMode;
  irImport?: string;
}

/**
 * Emit an ES6 module for a compiled component.
 *
 *   "linked" (default) / "bare" — import createDOP from @obinexusltd/obix-ir
 *   "inline" / "shared-inline"   — Level 1; throws UnsupportedFeatureError
 *
 * The `<script>` body is re-emitted verbatim (one shared definition of every
 * action — never four copies). The template descriptor is serialised and walked
 * by a small self-contained renderer.
 */
export function emitModule(ir: DopIR, script: ObixScriptModel, opts: EmitOptions = {}): string {
  const mode: EmitMode = opts.mode ?? "linked";
  if (mode === "inline" || mode === "shared-inline") {
    throw new UnsupportedFeatureError(`compiler emit mode "${mode}"`, 1);
  }
  const irImport = opts.irImport ?? "@obinexusltd/obix-ir";
  const N = ir.name;

  return `/* @generated by @obinexusltd/obix-compiler — OBIX ${ir.specVersion}, Level ${ir.level}, mode "${mode}" */
import { createDOP } from ${JSON.stringify(irImport)};

/* ---- verbatim <script> ---- */
${script.raw.trim()}
/* ---- end <script> ---- */

const __TEMPLATE = ${JSON.stringify(ir.template)};
const __STYLE = ${JSON.stringify(ir.style)};
const __ACTION_PROP_DEPS = ${JSON.stringify(mapPropDeps(ir))};
const __DERIVED_DEPS = ${JSON.stringify(ir.derivedDeps)};

function __esc(v) {
  return String(v == null ? "" : v)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function __resolve(expr, scope) {
  const parts = String(expr).trim().split(".");
  let cur = scope[parts[0]];
  for (let i = 1; i < parts.length && cur != null; i++) cur = cur[parts[i]];
  return cur;
}
function __renderEl(el, scope) {
  const cond = el.attrs.find((a) => a.directive === "conditional");
  if (cond && !__resolve(cond.value, scope)) return "";
  const VOID = new Set(["br", "hr", "img", "input", "meta", "link"]);
  const attrs = [];
  for (const a of el.attrs) {
    if (a.directive === "event" || a.directive === "conditional") continue;
    if (a.interpolation != null) {
      const v = __resolve(a.interpolation, scope);
      if (a.directive === "bool") { if (v) attrs.push(a.name); }
      else if (a.directive === "aria") attrs.push(a.name + '="' + (v === true ? "true" : v === false ? "false" : __esc(v)) + '"');
      else if (v != null && v !== false) attrs.push(a.name + '="' + (v === true ? "" : __esc(v)) + '"');
    } else if (a.value === null) attrs.push(a.name);
    else attrs.push(a.name + '="' + __esc(a.value) + '"');
  }
  const open = "<" + el.tag + (attrs.length ? " " + attrs.join(" ") : "") + ">";
  if (VOID.has(el.tag)) return open;
  const inner = el.children.map((c) => __renderNode(c, scope)).join("");
  return open + inner + "</" + el.tag + ">";
}
function __renderNode(node, scope) {
  if (node.kind === "text") return __esc(node.value).replace(/\\s+/g, " ");
  if (node.kind === "interpolation") return __esc(__resolve(node.expr, scope));
  return __renderEl(node, scope);
}
function __render(state, props) {
  const d = {};
  const src = (typeof derived !== "undefined" && derived) || {};
  for (const k of Object.keys(src)) { try { d[k] = src[k](state, props); } catch { d[k] = undefined; } }
  return __renderEl(__TEMPLATE.root, { ...props, ...state, ...d });
}
function __validate(state, props) {
  if (typeof validate === "function") return validate(state, props);
  return { valid: true, violations: [] };
}
function __normalizeEffects(raw) {
  const out = {};
  for (const [name, e] of Object.entries(raw || {})) {
    out[name] = {
      name,
      kind: e.every != null ? "every" : e.after != null ? "after" : "on",
      every: e.every,
      dispatch: e.dispatch,
      whileExpr: typeof e.while === "function" ? e.while.toString() : e.whileExpr,
      while: typeof e.while === "function" ? e.while : undefined,
    };
  }
  return out;
}

export const ${N}DOP = createDOP({
  name: ${JSON.stringify(N)},
  initialState: state,
  props: props,
  actions: actions,
  derived: typeof derived !== "undefined" ? derived : {},
  effects: __normalizeEffects(typeof effects !== "undefined" ? effects : {}),
  validate: __validate,
  render: __render,
  template: __TEMPLATE,
  style: __STYLE,
  actionPropDeps: __ACTION_PROP_DEPS,
  derivedDeps: __DERIVED_DEPS,
});

export default ${N}DOP;
`;
}

function mapPropDeps(ir: DopIR): Record<string, readonly string[]> {
  const out: Record<string, readonly string[]> = {};
  for (const [name, decl] of Object.entries(ir.actionDecls)) out[name] = decl.propDeps;
  return out;
}
